In [1]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [3]:
df = pd.read_excel('/Users/dongyokim/Library/Mobile Documents/com~apple~CloudDocs/2022:1/비즈니스 애널리틱스/실습/판별분석_실습_9주차 .xlsx', sheet_name='Data')

In [4]:
df

Income  Lot_Size Ownership
0     60.0      18.4     Owner
1     85.5      16.8     Owner
2     64.8      21.6     Owner
3     61.5      20.8     Owner
4     87.0      23.6     Owner
5    110.1      19.2     Owner
6    108.0      17.6     Owner
7     82.8      22.4     Owner
8     69.0      20.0     Owner
9     93.0      20.8     Owner
10    51.0      22.0     Owner
11    81.0      20.0     Owner
12    75.0      19.6  Nonowner
13    52.8      20.8  Nonowner
14    64.8      17.2  Nonowner
15    43.2      20.4  Nonowner
16    84.0      17.6  Nonowner
17    49.2      17.6  Nonowner
18    59.4      16.0  Nonowner
19    66.0      18.4  Nonowner
20    47.4      16.4  Nonowner
21    33.0      18.8  Nonowner
22    51.0      14.0  Nonowner
23    63.0      14.8  Nonowner

In [6]:
df_data = df[['Income', 'Lot_Size']]
df_target = df['Ownership']

In [8]:
# 데이터 정규 스케일링
df_scaled_data = StandardScaler().fit_transform(df_data)

In [9]:
df_scaled_data

array([[-0.43545243, -0.23136968],
       [ 0.88058157, -0.9044451 ],
       [-0.18772838,  1.11478117],
       [-0.35803866,  0.77824346],
       [ 0.95799534,  1.95612545],
       [ 2.15016731,  0.10516804],
       [ 2.04178804, -0.56790739],
       [ 0.7412368 ,  1.45131888],
       [ 0.02903016,  0.44170575],
       [ 1.26765039,  0.77824346],
       [-0.89993501,  1.28305003],
       [ 0.64834028,  0.44170575],
       [ 0.33868522,  0.27343689],
       [-0.80703849,  0.77824346],
       [-0.18772838, -0.73617625],
       [-1.30248659,  0.6099746 ],
       [ 0.80316781, -0.56790739],
       [-0.99283153, -0.56790739],
       [-0.46641793, -1.24098281],
       [-0.12579737, -0.23136968],
       [-1.08572805, -1.07271396],
       [-1.82890019, -0.06310082],
       [-0.89993501, -2.08232709],
       [-0.2806249 , -1.74578938]])

In [16]:
# 2개의 클래스로 구분하기 위한 LDA 생성
lda = LinearDiscriminantAnalysis(n_components=1)

In [17]:
# fit()호출 시 target값 입력 
lda.fit(df_scaled_data, df_target)
df_lda = lda.transform(df_scaled_data)

In [18]:
df_lda

array([[-0.61750748],
       [ 0.01064948],
       [ 0.82951029],
       [ 0.36601756],
       [ 2.66407504],
       [ 2.1132957 ],
       [ 1.40432086],
       [ 2.00517105],
       [ 0.42575032],
       [ 1.8920919 ],
       [ 0.31275353],
       [ 1.00711197],
       [ 0.564622  ],
       [-0.05546964],
       [-0.84039023],
       [-0.6723681 ],
       [ 0.24159755],
       [-1.44435124],
       [-1.55743039],
       [-0.32682665],
       [-1.98698291],
       [-1.77376206],
       [-2.72342924],
       [-1.83844931]])

In [21]:
from sklearn.metrics import accuracy_score
pred = lda.predict(df_scaled_data)
print(accuracy_score(df_target, pred))

0.875


In [101]:
df = pd.read_excel('/Users/dongyokim/Library/Mobile Documents/com~apple~CloudDocs/2022:1/비즈니스 애널리틱스/Data/Accidents.xlsx', sheet_name='Data')

In [102]:
df = pd.concat([df, pd.get_dummies(df['LGTCON_I_R'], prefix='LGTCON_I_R')],axis=1)

In [103]:
df.drop(columns='LGTCON_I_R', inplace=True)

In [104]:
df = pd.concat([df, pd.get_dummies(df['SUR_COND'], prefix='SUR_COND')],axis=1)

In [105]:
df.drop(columns='SUR_COND', inplace=True)

In [106]:
df = pd.concat([df, pd.get_dummies(df['TRAF_WAY'], prefix='TRAF_WAY')],axis=1)

In [107]:
df.drop(columns='TRAF_WAY', inplace=True)

In [128]:
df

HOUR_I_R  ALCHL_I  ALIGN_I  STRATUM_R  WRK_ZONE  WKDY_I_R  INT_HWY  \
0             0        2        2          1         0         1        0   
1             1        2        1          0         0         1        1   
2             1        2        1          0         0         1        0   
3             1        2        1          1         0         0        0   
4             1        1        1          0         0         1        0   
...         ...      ...      ...        ...       ...       ...      ...   
42178         0        2        1          0         1         1        0   
42179         1        2        1          1         0         0        0   
42180         0        2        2          0         0         1        0   
42181         1        2        1          1         0         1        0   
42182         1        2        1          0         1         1        0   

       MANCOL_I_R  PED_ACC_R  RELJCT_I_R  ...  LGTCON_I_R_2  LGTCON_I_R_3  \
0               0          0           1  ...             0             1   
1               2          0           1  ...             0             1   
2               2          0           1  ...             0             1   
3               2          0           1  ...             0             1   
4               2          0           0  ...             0             1   
...           ...        ...         ...  ...           ...           ...   
42178           0          0           0  ...             0             0   
42179           0          0           1  ...             0             0   
42180           0          0           0  ...             0             0   
42181           0          0           0  ...             0             0   
42182           0          1           0  ...             0             0   

       SUR_COND_1  SUR_COND_2  SUR_COND_3  SUR_COND_4  SUR_COND_9  TRAF_WAY_1  \
0               0           0           0           1           0           0   
1               0           0           0           1           0           0   
2               0           0           0           1           0           0   
3               0           0           0           1           0           0   
4               0           0           0           1           0           0   
...           ...         ...         ...         ...         ...         ...   
42178           1           0           0           0           0           1   
42179           1           0           0           0           0           1   
42180           1           0           0           0           0           1   
42181           1           0           0           0           0           1   
42182           1           0           0           0           0           1   

       TRAF_WAY_2  TRAF_WAY_3  
0               0           1  
1               0           1  
2               1           0  
3               1           0  
4               1           0  
...           ...         ...  
42178           0           0  
42179           0           0  
42180           0           0  
42181           0           0  
42182           0           0  

[42183 rows x 32 columns]

In [137]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='MAX_SEV_IR') , df['MAX_SEV_IR'], test_size=0.4, random_state=0) 

In [138]:
lda = LinearDiscriminantAnalysis(n_components=2)

lda.fit(X_train, y_train)

train_pred = lda.predict(X_train)

print('학습 데이터의 정확도: {0:.4f}'.format(accuracy_score(y_train, train_pred)))
print('학습 데이터의 confusion matrix :\n {}'.format(confusion_matrix(y_train, train_pred)))

학습 데이터의 정확도: 0.9755
학습 데이터의 confusion matrix :
 [[12433     9     0]
 [  198 12230   167]
 [    0   246    26]]


In [139]:
test_pred = lda.predict(X_test)
print('검증 데이터의 정확도: {0:.4f}'. format(accuracy_score(y_test, test_pred)))
print('학습 데이터의 confusion matrix :\n {}'.format(confusion_matrix(y_test, test_pred)))

검증 데이터의 정확도: 0.9764
학습 데이터의 confusion matrix :
 [[8273    6    0]
 [ 108 8184  109]
 [   0  175   19]]
